name: CI

on: pull_request

jobs:
  lint-and-audit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['7.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

     - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer, cs2pr

      - name: Use desired version of NodeJS
        uses: actions/setup-node@v3
        with:
            node-version: 14.15
            cache: 'npm'

       - name: Install composer dependencies
        run: composer config github-oauth.github.com ${{ secrets.PRIVATE_ACCESS_TOKEN }} && composer install --prefer-dist --no-suggest --no-progress

      - name: Run phpcs
        id: phpcs
        if: always()
        run: ./vendor/bin/phpcs --report-full --report-checkstyle=./phpcs-report.xml

      - name: npm install, build
        run: npm ci

      - name: Start Docker environment
        run: npm run env:start
        env:
          COMPOSE_INTERACTIVE_NO_CLI: true

      - name: E2E Tests
        if: always()
        run: npm run test:e2e:ci

      - name: Stop Docker environment
        run: npm run env:stop
        if: always()
        env:
          COMPOSE_INTERACTIVE_]NO_CLI: true

      - name: Lint JS
        run: npm run lint:js